export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'; 
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'; 

export const ALL_PRODUCTS = 'ALL_PRODUCTS';
export const ALL_PRODUCTS_SUCCESS = 'ALL_PRODUCTS_SUCCESS';
export const ALL_PRODUCTS_ERROR = 'ALL_PRODUCTS_ERROR';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_ERROR = 'DELETE_PRODUCT_ERROR';

export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const EDIT_PRODUCT_START = 'EDIT_PRODUCT_START';
export const EDITED_PRODUCT_SUCCESS = 'EDITED_PRODUCT_SUCCESS';
export const EDITED_PRODUCT_ERROR = 'EDITED_PRODUCT_ERROR';
